enum MenuChoise { 
    DECREASE_AMBIENT,
    INCREASE_AMBIENT,
    DECREASE_AMBIENT_RED,
    INCREASE_AMBIENT_RED,
    DECREASE_AMBIENT_GREEN,
    INCREASE_AMBIENT_GREEN,
    DECREASE_AMBIENT_BLUE,
    INCREASE_AMBIENT_BLUE,
    RESET_VIEW,
    DECREASE_CAMERA_X,
    INCREASE_CAMERA_X,
    DECREASE_CAMERA_Y,
    INCREASE_CAMERA_Y,
    DECREASE_CAMERA_Z,
    INCREASE_CAMERA_Z,
    ELEPHANT_VIEW,
    HELP,
    QUIT
};

enum Action {
    MOVE_HEAD,
    MOVE_TAIL,
    WALK,
    MOVE_CAMERA,
    CHANGE_AMBIENT_LIGHT,
    NONE
};

#define WINDOW_WIDTH 1000
#define WINDOW_HEIGHT 1000
#define HELP_MENU_WIDTH 300
#define HELP_MENU_HEIGHT 300
#define CONTROL_PANEL_HEIGHT WINDOW_HEIGHT/4
#define WINDOW_POS_X 500
#define WINDOW_POS_Y 50
#define CAMERA_INITIAL_POS_X 0.0
#define CAMERA_INITIAL_POS_Y 12.0
#define CAMERA_INITIAL_POS_Z 30.0
#define Z_NEAR 2.0
#define Z_FAR 500.0
#define NUM_TREES 50
